### PR TITLE
Feature - Authentication

### PR DESCRIPTION
**Pull request by v-stamenova**
The following PR request closes issues - #23, #24, #35, #32, #13

Before testing within `variables.env` in the API Gateway create a new var JWT_SECRET. Set a value for it of your choice. Don't forget to install the new packages in case they are not autoinstalled in the docker containers. 

For testing: 
- [x] User can register
- [x] Proper errors when registering
- [x] Unique email constraint
- [x] Proper styling for registering errors
- [x] User can login
- [x] Proper errors when login
- [x] Proper styling for login errors
- [x] /habits not accessible unless the user is authenticated

I am aware that there is an issue with the background of the design, but it wasn't the highest priority in this PR

### CODE REVIEW

**Comment by DanielBartha** [comment]
I personally think that the errors when logging in or registering should appear underneath the input field. Other than that everything seems completely fine after testing.

**Review by DanielBartha — COMMENTED** [review]
Other than the styling of error messages on input fields everything worked as expected. gud jeb

**Comment by LauraBirau** [comment]
Everything worked fine for me. Good job!!

**Review by LauraBirau — COMMENTED** [review]
Everything works fine. Good job!

**Pull request merged**
